//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShop.DataAccess
{

    public partial class Account
    {
        public int AccountId { get; set; }
        public string AccountName { get; set; }
        public int UserType { get; set; }
        public string Password { get; set; }
    
        public virtual UserType UserType1 { get; set; }
    }
}
